name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    # 1. Runs the job on an environment
    environment: production 
    
    # 2. Runs the job on a virtual machine
    runs-on: ubuntu-latest
    
    steps:
      # 3. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 4. (If applicable) Set up your language runtime, e.g., Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 5. (If applicable) Build the project
      - name: Build Project
        run: |
          npm install
          npm run build
      
      # 6. Deploy to a hosting provider using an action
      # This step is highly dependent on your actual hosting service (AWS, Azure, Netlify, etc.)
      - name: Deploy to Azure Web App (Example)
        uses: azure/webapps-deploy@v2
        with:
          # This secret is retrieved from the 'production' environment secrets
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
          app-name: 'my-production-app'
          package: './dist'
